name: Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libssl-dev git subversion

      - name: Update feeds
        run: |
          ./scripts/feeds update
          ./scripts/feeds install -a

      - name: Generate full config
        run: make defconfig V=s

      - name: Download dependencies
        run: make download -j$(nproc) V=s

      - name: Run full build
        run: make -j$(nproc) V=s

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: bin/
